cutLogMaterials:
  - LOG
  - LOG_2
  - LEGACY_LOG
  - LEGACY_LOG_2
  - ACACIA_LOG
  - BIRCH_LOG
  - DARK_OAK_LOG
  - JUNGLE_LOG
  - OAK_LOG
  - SPRUCE_LOG
  - CRIMSON_STEM
  - WARPED_STEM

oreMaterial:
  - COAL_ORE
  - IRON_ORE
  - REDSTONE_ORE
  - GOLD_ORE
  - DIAMOND_ORE
  - COPPER_ORE
  - LAPIS_ORE
  - EMERALD_ORE
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_EMERALD_ORE
  - NETHER_GOLD_ORE
  - NETHER_QUARTZ_ORE
  - ANCIENT_DEBRIS