name: EasyBreaking
version: '${version}'
main: easybreaking.easybreaking.EasyBreaking
api-version: 1.18

permissions:
  CutAll:
    default: false
  MineAll:
    default: false

commands:
  CutAll:
    description: CutAll

  MineAll:
    description: MineAll

